export const storageKeys = {
  bottomDrawerHeightPx: 'fractalframe:bottomDrawerHeightPx:v1',
  bottomDrawerOpen: 'fractalframe:bottomDrawerOpen:v1',
  chartColorPaletteCustomColors: 'ffChartColorPaletteCustomColorsV1',
  importCenterColumnWidthsPx: 'fractalframe:mt5ImportCenterColumnWidthsPx:v1',
  importCenterM1CheckResults: 'fractalframe:mt5ImportCenterM1CheckResults:v1',
  importCenterQuery: 'fractalframe:mt5ImportCenterQuery:v1',
  importCenterSelectedTab: 'fractalframe:mt5ImportCenterSelectedTab:v1',
  importCenterShortcutMenuEnabled: 'fractalframe:mt5ImportCenterShortcutMenuEnabled:v1',
  importCenterShortcutMenuPeriods: 'fractalframe:mt5ImportCenterShortcutMenuPeriods:v1',
  importCenterSharedSelection: 'fractalframe:mt5ImportCenterSharedSelection:v1',
  importCenterStorePanelPersistenceEnabled: 'fractalframe:mt5ImportCenterStorePanelPersistenceEnabled:v1',
  importCenterStorePanelSelectedTableKey: 'fractalframe:mt5ImportCenterStorePanelSelectedTableKey:v1',
  importCenterStoreAggregateTableHeightPx: 'fractalframe:mt5ImportCenterStoreAggregateTableHeightPx:v1',
  importCenterStoreV6ListSymbols: 'fractalframe:mt5ImportCenterStoreV6ListSymbols:v1',
  importCenterStoreV6Status: 'fractalframe:mt5ImportCenterStoreV6Status:v1',
  importCenterSymbolSnapshot: 'fractalframe:mt5ImportCenterSymbolSnapshot:v1',
  importCenterTopPaneHeightPx: 'fractalframe:mt5ImportCenterTopPaneHeightPx:v1',
  importCenterWatchlistRealtimeEnabled: 'fractalframe:mt5ImportCenterWatchlistRealtimeEnabled:v1',
  importCenterWatchlistRealtimeSnapshot: 'fractalframe:mt5ImportCenterWatchlistRealtimeSnapshot:v1',
  importCenterWatchlistSymbols: 'fractalframe:mt5ImportCenterWatchlistSymbols:v1',
  importCenterWatchlistColumnWidthsPx: 'fractalframe:mt5ImportCenterWatchlistColumnWidthsPx:v1',
  importCenterWatchlistTableHeightPx: 'fractalframe:mt5ImportCenterWatchlistTableHeightPx:v1',
  marketStatusTitleSnapshots: 'fractalframe:marketStatusTitleSnapshots:v1',
  // Legacy key kept by chartRealtimeBridge as a fallback until the realtime profile is migrated.
  realtimePageBuffer: 'fractalframe:chartRealtimePageBuffer:v1',
  renderPageConfig: 'fractalframe:klinechart-v2:renderPageConfig:v1',
  // Legacy realtime monitor snapshot key; do not add new V2 state here.
  realtimePageSnapshot: 'fractalframe:chartRealtimePageSnapshot:v1',
  realtimePageTableHeightPx: 'fractalframe:chartRealtimePageTableHeightPx:v1',
  // Legacy realtime page index cache key; V2 runtime state should use klinechart-v2 keys.
  realtimePageIndexCache: 'fractalframe:chartRealtimePageIndexCache:v1',
  realtimePageLastResetCache: 'fractalframe:chartRealtimePageLastResetCache:v1',
  realtimeStablePage: 'fractalframe:klinechart-v2:realtimeStablePage:v1',
  realtimeTailRuntime: 'fractalframe:klinechart-v2:realtimeTailRuntime:v1',
  indicatorShortcutKeys: 'fractalframe:indicatorShortcutKeys:v1',
  strategyLoadedKeys: 'fractalframe:strategyLoadedKeys:v1',
  strategyDrawerActiveTab: 'fractalframe:strategyDrawerActiveTab:v1',
  strategyDrawerColumnWidthsPx: 'fractalframe:strategyDrawerColumnWidthsPx:v1',
  strategyDrawerSelectedKey: 'fractalframe:strategyDrawerSelectedKey:v1',
  strategyDrawerTopHeightPx: 'fractalframe:strategyDrawerTopHeightPx:v1',
  strategyPersistenceEnabled: 'fractalframe:strategyPersistenceEnabled:v1',
  strategyShortcutKeys: 'fractalframe:strategyShortcutKeys:v1',
  rightWidgetActiveDrawer: 'fractalframe:rightWidgetActiveDrawer:v1',
  rightWidgetDrawerWidthPx: 'fractalframe:rightWidgetDrawerWidthPx:v1',
  settingsSymbolPanel: 'fractalframe:settingsSymbolPanel:v1',
} as const

export type StorageKeyName = keyof typeof storageKeys
