export const chartSettingKeys = {
  pricePrecision: 'price.precision',
  timezone: 'time.timezone',
  statusTitleVisible: 'status.title.visible',
  statusTitleMode: 'status.title.mode',
  statusLocalDataLoadVisible: 'status.localDataLoad.visible',
  statusChartValuesVisible: 'status.chartValues.visible',
  statusCandleChangeVisible: 'status.candleChange.visible',
  statusCandleVolumeVisible: 'status.candleVolume.visible',
  statusCandleTimeVisible: 'status.candleTime.visible',
  currentCandleCountdownVisible: 'coordinates.currentCandleCountdown.visible',
  rightPlaceholderVisible: 'coordinates.rightPlaceholder.visible',
  statusIndicatorTitleVisible: 'status.indicatorTitle.visible',
  statusIndicatorTooltipVisible: 'status.indicatorTooltip.visible',
  statusIndicatorInputsVisible: 'status.indicatorInputs.visible',
  statusIndicatorValuesVisible: 'status.indicatorValues.visible',
  sessionBreakVisible: 'events.sessionBreak.visible',
} as const

export const chartSettingDefaults = {
  pricePrecision: 'system',
  timezone: 'UTC',
  statusTitleVisible: true,
  statusTitleMode: 'symbol-name',
  statusLocalDataLoadVisible: true,
  statusChartValuesVisible: true,
  statusCandleChangeVisible: true,
  statusCandleVolumeVisible: true,
  statusCandleTimeVisible: true,
  currentCandleCountdownVisible: true,
  rightPlaceholderVisible: false,
  statusIndicatorTitleVisible: true,
  statusIndicatorTooltipVisible: true,
  statusIndicatorInputsVisible: true,
  statusIndicatorValuesVisible: true,
  sessionBreakVisible: false,
} as const
