import {
  createStoreV6IndicatorRegistryV2,
  storeV6AoIndicatorDefinitionV2,
  storeV6DpoIndicatorDefinitionV2,
  storeV6MaIndicatorDefinitionV2,
  storeV6MacdIndicatorDefinitionV2,
  storeV6MmadIndicatorDefinitionV2,
  storeV6MmfV3IndicatorDefinitionV2,
  storeV6MmfStochH2IndicatorDefinitionV2,
  storeV6MorganRangeM5IndicatorDefinitionV2,
  storeV6MorganRangeM30IndicatorDefinitionV2,
  storeV6MorganRangeH2IndicatorDefinitionV2,
  storeV6RsiIndicatorDefinitionV2,
  storeV6SqzmomIndicatorDefinitionV2,
  storeV6StochIndicatorDefinitionV2,
  storeV6TsiIndicatorDefinitionV2,
  storeV6VdoIndicatorDefinitionV2,
  storeV6ViIndicatorDefinitionV2,
  storeV6VmiIndicatorDefinitionV2,
  storeV6VolIndicatorDefinitionV2,
  storeV6VwapIndicatorDefinitionV2,
} from './indicatorRequestV2'

export const chartWorkspaceIndicatorRegistryV2 = createStoreV6IndicatorRegistryV2()

chartWorkspaceIndicatorRegistryV2.register(storeV6MaIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MmfV3IndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MmfStochH2IndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MorganRangeM5IndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MorganRangeM30IndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MorganRangeH2IndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6VolIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6VwapIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6RsiIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6SqzmomIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MacdIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6DpoIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6StochIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6TsiIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6AoIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6VdoIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6VmiIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6MmadIndicatorDefinitionV2)
chartWorkspaceIndicatorRegistryV2.register(storeV6ViIndicatorDefinitionV2)
