import type { MmfIndicatorSettings } from '../rightDrawer/indicatorPersistence'
import type { MmfV2IndicatorMarker } from '../../services/mt5/mmfV2IndicatorApi'
import type { MmfV2IndicatorRow } from './mmfV2Types'

export type MmfV2SignalVisualId =
  | MmfV2IndicatorMarker['type']
  | 'MMF_V2_DEAD_CROSS'
  | 'MMF_V2_GOLDEN_CROSS'
  | 'MMF_V2_HIGH_CONFIRM_POINT'
  | 'MMF_V2_LOW_CONFIRM_POINT'

export type MmfV2SignalCatalogEntry = {
  id: MmfV2SignalVisualId
  sourceMarkerType: MmfV2IndicatorMarker['type']
  label: string
  category: 'stoch' | 'level' | 'trend' | 'break'
  direction: 'up' | 'down' | 'support' | 'resistance' | 'neutral'
  role: string
  timing: 'current' | 'delayed'
  layer: 'base' | 'replacement' | 'outer' | 'event'
  strategyIntent: string
  markerKey: keyof Pick<MmfV2IndicatorRow, 'highMarker' | 'deadCrossMarker' | 'lowMarker' | 'goldenCrossMarker' | 'highConfirmPointMarker' | 'lowConfirmPointMarker' | 'supportMarker' | 'resistanceMarker' | 'expectedSupportMarker' | 'expectedResistanceMarker' | 'trendDownReboundMarker' | 'trendUpPullbackMarker' | 'trendDownReturnMarker' | 'trendUpReturnMarker' | 'trendDownDivergenceMarker' | 'trendUpDivergenceMarker' | 'supportDownBreakMarker' | 'supportUpBreakMarker' | 'resistanceDownBreakMarker' | 'resistanceUpBreakMarker'>
  priceKey: keyof Pick<MmfV2IndicatorRow, 'highMarkerPrice' | 'deadCrossMarkerPrice' | 'lowMarkerPrice' | 'goldenCrossMarkerPrice' | 'highConfirmPointMarkerPrice' | 'lowConfirmPointMarkerPrice' | 'supportMarkerPrice' | 'resistanceMarkerPrice' | 'expectedSupportMarkerPrice' | 'expectedResistanceMarkerPrice' | 'trendDownReboundMarkerPrice' | 'trendUpPullbackMarkerPrice' | 'trendDownReturnMarkerPrice' | 'trendUpReturnMarkerPrice' | 'trendDownDivergenceMarkerPrice' | 'trendUpDivergenceMarkerPrice' | 'supportDownBreakMarkerPrice' | 'supportUpBreakMarkerPrice' | 'resistanceDownBreakMarkerPrice' | 'resistanceUpBreakMarkerPrice'>
  distanceKey?: keyof Pick<MmfV2IndicatorRow, 'highConfirmPointDistance' | 'lowConfirmPointDistance'>
  showKey: keyof Pick<MmfIndicatorSettings, 'showHigh' | 'showDeadCross' | 'showLow' | 'showGoldenCross' | 'showHighConfirmPoint' | 'showLowConfirmPoint' | 'showSupportLevel' | 'showResistanceLevel' | 'showExpectedSupportLevel' | 'showExpectedResistanceLevel' | 'showTrendDownReboundPoint' | 'showTrendUpPullbackPoint' | 'showTrendDownReturnPoint' | 'showTrendUpReturnPoint' | 'showTrendDownDivergencePointV2' | 'showTrendUpDivergencePointV2' | 'showSupportDownBreakPoint' | 'showSupportUpBreakPoint' | 'showResistanceDownBreakPoint' | 'showResistanceUpBreakPoint'>
  colorKey: keyof Pick<MmfIndicatorSettings, 'highColor' | 'deadCrossColor' | 'lowColor' | 'goldenCrossColor' | 'highConfirmPointColor' | 'lowConfirmPointColor' | 'supportColor' | 'resistanceColor' | 'expectedSupportColor' | 'expectedResistanceColor' | 'trendDownReboundColor' | 'trendUpPullbackColor' | 'trendDownReturnColor' | 'trendUpReturnColor' | 'trendDownDivergencePointColor' | 'trendUpDivergencePointColor' | 'supportDownBreakColor' | 'supportUpBreakColor' | 'resistanceDownBreakColor' | 'resistanceUpBreakColor'>
  sizeKey: keyof Pick<MmfIndicatorSettings, 'highSize' | 'deadCrossSize' | 'lowSize' | 'goldenCrossSize' | 'highConfirmPointSize' | 'lowConfirmPointSize' | 'supportSize' | 'resistanceSize' | 'expectedSupportSize' | 'expectedResistanceSize' | 'trendDownReboundSize' | 'trendUpPullbackSize' | 'trendDownReturnSize' | 'trendUpReturnSize' | 'trendDownDivergencePointSize' | 'trendUpDivergencePointSize' | 'supportDownBreakSize' | 'supportUpBreakSize' | 'resistanceDownBreakSize' | 'resistanceUpBreakSize'>
  symbolKey: keyof Pick<MmfIndicatorSettings, 'highSymbol' | 'deadCrossSymbol' | 'lowSymbol' | 'goldenCrossSymbol' | 'highConfirmPointSymbol' | 'lowConfirmPointSymbol' | 'supportSymbol' | 'resistanceSymbol' | 'expectedSupportSymbol' | 'expectedResistanceSymbol' | 'trendDownReboundSymbol' | 'trendUpPullbackSymbol' | 'trendDownReturnSymbol' | 'trendUpReturnSymbol' | 'trendDownDivergencePointSymbol' | 'trendUpDivergencePointSymbol' | 'supportDownBreakSymbol' | 'supportUpBreakSymbol' | 'resistanceDownBreakSymbol' | 'resistanceUpBreakSymbol'>
  defaultStyle: {
    color: string
    offsetMultiplier: number
    placement: 'above' | 'below'
    size: number
    symbol: string
  }
  replaces: Array<keyof MmfV2IndicatorRow>
}

export const mmfV2SignalCatalog: MmfV2SignalCatalogEntry[] = [
  { id: 'MMF_V2_DEAD_CROSS', sourceMarkerType: 'MMF_V2_HIGH', label: '死叉', category: 'stoch', direction: 'down', role: 'dead_cross', timing: 'current', layer: 'base', strategyIntent: 'cross_reference', markerKey: 'deadCrossMarker', priceKey: 'deadCrossMarkerPrice', showKey: 'showDeadCross', colorKey: 'deadCrossColor', sizeKey: 'deadCrossSize', symbolKey: 'deadCrossSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.55, placement: 'above', size: 16, symbol: '\u2715' }, replaces: [] },
  { id: 'MMF_V2_HIGH', sourceMarkerType: 'MMF_V2_HIGH', label: 'High', category: 'stoch', direction: 'down', role: 'base_high', timing: 'current', layer: 'base', strategyIntent: 'structure_reference', markerKey: 'highMarker', priceKey: 'highMarkerPrice', showKey: 'showHigh', colorKey: 'highColor', sizeKey: 'highSize', symbolKey: 'highSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: [] },
  { id: 'MMF_V2_TREND_UP_DIVERGENCE', sourceMarkerType: 'MMF_V2_TREND_UP_DIVERGENCE', label: '上升趋势 - 背离点', category: 'trend', direction: 'up', role: 'divergence_point', timing: 'current', layer: 'replacement', strategyIntent: 'long_confirmation_candidate', markerKey: 'trendUpDivergenceMarker', priceKey: 'trendUpDivergenceMarkerPrice', showKey: 'showTrendUpDivergencePointV2', colorKey: 'trendUpDivergencePointColor', sizeKey: 'trendUpDivergencePointSize', symbolKey: 'trendUpDivergencePointSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: ['highMarker', 'highMarkerPrice'] },
  { id: 'MMF_V2_EXPECTED_RESISTANCE', sourceMarkerType: 'MMF_V2_EXPECTED_RESISTANCE', label: '预期阻力位', category: 'level', direction: 'resistance', role: 'expected_level', timing: 'current', layer: 'replacement', strategyIntent: 'resistance_candidate', markerKey: 'expectedResistanceMarker', priceKey: 'expectedResistanceMarkerPrice', showKey: 'showExpectedResistanceLevel', colorKey: 'expectedResistanceColor', sizeKey: 'expectedResistanceSize', symbolKey: 'expectedResistanceSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c7' }, replaces: ['highMarker', 'highMarkerPrice'] },
  { id: 'MMF_V2_RESISTANCE', sourceMarkerType: 'MMF_V2_RESISTANCE', label: '阻力位', category: 'level', direction: 'resistance', role: 'confirmed_level', timing: 'delayed', layer: 'outer', strategyIntent: 'resistance_reference', markerKey: 'resistanceMarker', priceKey: 'resistanceMarkerPrice', showKey: 'showResistanceLevel', colorKey: 'resistanceColor', sizeKey: 'resistanceSize', symbolKey: 'resistanceSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: [] },
  { id: 'MMF_V2_TREND_DOWN_REBOUND', sourceMarkerType: 'MMF_V2_TREND_DOWN_REBOUND', label: '下降趋势 - 反弹点', category: 'trend', direction: 'down', role: 'rebound_point', timing: 'current', layer: 'replacement', strategyIntent: 'short_watch', markerKey: 'trendDownReboundMarker', priceKey: 'trendDownReboundMarkerPrice', showKey: 'showTrendDownReboundPoint', colorKey: 'trendDownReboundColor', sizeKey: 'trendDownReboundSize', symbolKey: 'trendDownReboundSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: ['highMarker', 'highMarkerPrice'] },
  { id: 'MMF_V2_TREND_DOWN_RETURN', sourceMarkerType: 'MMF_V2_TREND_DOWN_RETURN', label: '下降趋势 - 回归点', category: 'trend', direction: 'down', role: 'return_point', timing: 'current', layer: 'replacement', strategyIntent: 'short_entry_candidate', markerKey: 'trendDownReturnMarker', priceKey: 'trendDownReturnMarkerPrice', showKey: 'showTrendDownReturnPoint', colorKey: 'trendDownReturnColor', sizeKey: 'trendDownReturnSize', symbolKey: 'trendDownReturnSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: ['trendDownReboundMarker', 'trendDownReboundMarkerPrice', 'highMarker', 'highMarkerPrice'] },
  { id: 'MMF_V2_GOLDEN_CROSS', sourceMarkerType: 'MMF_V2_LOW', label: '金叉', category: 'stoch', direction: 'up', role: 'golden_cross', timing: 'current', layer: 'base', strategyIntent: 'cross_reference', markerKey: 'goldenCrossMarker', priceKey: 'goldenCrossMarkerPrice', showKey: 'showGoldenCross', colorKey: 'goldenCrossColor', sizeKey: 'goldenCrossSize', symbolKey: 'goldenCrossSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.55, placement: 'below', size: 16, symbol: '\u2715' }, replaces: [] },
  { id: 'MMF_V2_HIGH_CONFIRM_POINT', sourceMarkerType: 'MMF_V2_HIGH', label: '高点确认点', category: 'stoch', direction: 'down', role: 'confirm_point', timing: 'delayed', layer: 'base', strategyIntent: 'high_confirm_reference', markerKey: 'highConfirmPointMarker', priceKey: 'highConfirmPointMarkerPrice', distanceKey: 'highConfirmPointDistance', showKey: 'showHighConfirmPoint', colorKey: 'highConfirmPointColor', sizeKey: 'highConfirmPointSize', symbolKey: 'highConfirmPointSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.75, placement: 'above', size: 16, symbol: '\u2193' }, replaces: [] },
  { id: 'MMF_V2_LOW', sourceMarkerType: 'MMF_V2_LOW', label: 'Low', category: 'stoch', direction: 'up', role: 'base_low', timing: 'current', layer: 'base', strategyIntent: 'structure_reference', markerKey: 'lowMarker', priceKey: 'lowMarkerPrice', showKey: 'showLow', colorKey: 'lowColor', sizeKey: 'lowSize', symbolKey: 'lowSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: [] },
  { id: 'MMF_V2_TREND_DOWN_DIVERGENCE', sourceMarkerType: 'MMF_V2_TREND_DOWN_DIVERGENCE', label: '下降趋势 - 背离点', category: 'trend', direction: 'down', role: 'divergence_point', timing: 'current', layer: 'replacement', strategyIntent: 'short_confirmation_candidate', markerKey: 'trendDownDivergenceMarker', priceKey: 'trendDownDivergenceMarkerPrice', showKey: 'showTrendDownDivergencePointV2', colorKey: 'trendDownDivergencePointColor', sizeKey: 'trendDownDivergencePointSize', symbolKey: 'trendDownDivergencePointSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: ['lowMarker', 'lowMarkerPrice'] },
  { id: 'MMF_V2_EXPECTED_SUPPORT', sourceMarkerType: 'MMF_V2_EXPECTED_SUPPORT', label: '预期支撑位', category: 'level', direction: 'support', role: 'expected_level', timing: 'current', layer: 'replacement', strategyIntent: 'support_candidate', markerKey: 'expectedSupportMarker', priceKey: 'expectedSupportMarkerPrice', showKey: 'showExpectedSupportLevel', colorKey: 'expectedSupportColor', sizeKey: 'expectedSupportSize', symbolKey: 'expectedSupportSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c7' }, replaces: ['lowMarker', 'lowMarkerPrice'] },
  { id: 'MMF_V2_SUPPORT', sourceMarkerType: 'MMF_V2_SUPPORT', label: '支撑位', category: 'level', direction: 'support', role: 'confirmed_level', timing: 'delayed', layer: 'outer', strategyIntent: 'support_reference', markerKey: 'supportMarker', priceKey: 'supportMarkerPrice', showKey: 'showSupportLevel', colorKey: 'supportColor', sizeKey: 'supportSize', symbolKey: 'supportSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: [] },
  { id: 'MMF_V2_TREND_UP_PULLBACK', sourceMarkerType: 'MMF_V2_TREND_UP_PULLBACK', label: '上升趋势 - 回撤点', category: 'trend', direction: 'up', role: 'pullback_point', timing: 'current', layer: 'replacement', strategyIntent: 'long_watch', markerKey: 'trendUpPullbackMarker', priceKey: 'trendUpPullbackMarkerPrice', showKey: 'showTrendUpPullbackPoint', colorKey: 'trendUpPullbackColor', sizeKey: 'trendUpPullbackSize', symbolKey: 'trendUpPullbackSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: ['lowMarker', 'lowMarkerPrice'] },
  { id: 'MMF_V2_TREND_UP_RETURN', sourceMarkerType: 'MMF_V2_TREND_UP_RETURN', label: '上升趋势 - 回归点', category: 'trend', direction: 'up', role: 'return_point', timing: 'current', layer: 'replacement', strategyIntent: 'long_entry_candidate', markerKey: 'trendUpReturnMarker', priceKey: 'trendUpReturnMarkerPrice', showKey: 'showTrendUpReturnPoint', colorKey: 'trendUpReturnColor', sizeKey: 'trendUpReturnSize', symbolKey: 'trendUpReturnSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: ['trendUpPullbackMarker', 'trendUpPullbackMarkerPrice', 'lowMarker', 'lowMarkerPrice'] },
  { id: 'MMF_V2_SUPPORT_DOWN_BREAK', sourceMarkerType: 'MMF_V2_SUPPORT_DOWN_BREAK', label: '支撑位向下突破', category: 'break', direction: 'down', role: 'trend_open', timing: 'current', layer: 'event', strategyIntent: 'downtrend_open', markerKey: 'supportDownBreakMarker', priceKey: 'supportDownBreakMarkerPrice', showKey: 'showSupportDownBreakPoint', colorKey: 'supportDownBreakColor', sizeKey: 'supportDownBreakSize', symbolKey: 'supportDownBreakSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: ['highMarker', 'highMarkerPrice', 'resistanceMarker', 'resistanceMarkerPrice'] },
  { id: 'MMF_V2_SUPPORT_UP_BREAK', sourceMarkerType: 'MMF_V2_SUPPORT_UP_BREAK', label: '支撑位向上突破', category: 'break', direction: 'up', role: 'trend_close', timing: 'current', layer: 'event', strategyIntent: 'downtrend_close', markerKey: 'supportUpBreakMarker', priceKey: 'supportUpBreakMarkerPrice', showKey: 'showSupportUpBreakPoint', colorKey: 'supportUpBreakColor', sizeKey: 'supportUpBreakSize', symbolKey: 'supportUpBreakSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: ['lowMarker', 'lowMarkerPrice', 'supportMarker', 'supportMarkerPrice'] },
  { id: 'MMF_V2_RESISTANCE_UP_BREAK', sourceMarkerType: 'MMF_V2_RESISTANCE_UP_BREAK', label: '阻力位向上突破', category: 'break', direction: 'up', role: 'trend_open', timing: 'current', layer: 'event', strategyIntent: 'uptrend_open', markerKey: 'resistanceUpBreakMarker', priceKey: 'resistanceUpBreakMarkerPrice', showKey: 'showResistanceUpBreakPoint', colorKey: 'resistanceUpBreakColor', sizeKey: 'resistanceUpBreakSize', symbolKey: 'resistanceUpBreakSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.25, placement: 'below', size: 24, symbol: '\u25c6' }, replaces: ['lowMarker', 'lowMarkerPrice', 'supportMarker', 'supportMarkerPrice'] },
  { id: 'MMF_V2_RESISTANCE_DOWN_BREAK', sourceMarkerType: 'MMF_V2_RESISTANCE_DOWN_BREAK', label: '阻力位向下突破', category: 'break', direction: 'down', role: 'trend_close', timing: 'current', layer: 'event', strategyIntent: 'uptrend_close', markerKey: 'resistanceDownBreakMarker', priceKey: 'resistanceDownBreakMarkerPrice', showKey: 'showResistanceDownBreakPoint', colorKey: 'resistanceDownBreakColor', sizeKey: 'resistanceDownBreakSize', symbolKey: 'resistanceDownBreakSymbol', defaultStyle: { color: '#ef5350', offsetMultiplier: 0.25, placement: 'above', size: 24, symbol: '\u25c6' }, replaces: ['highMarker', 'highMarkerPrice', 'resistanceMarker', 'resistanceMarkerPrice'] },
  { id: 'MMF_V2_LOW_CONFIRM_POINT', sourceMarkerType: 'MMF_V2_LOW', label: '低点确认点', category: 'stoch', direction: 'up', role: 'confirm_point', timing: 'delayed', layer: 'base', strategyIntent: 'low_confirm_reference', markerKey: 'lowConfirmPointMarker', priceKey: 'lowConfirmPointMarkerPrice', distanceKey: 'lowConfirmPointDistance', showKey: 'showLowConfirmPoint', colorKey: 'lowConfirmPointColor', sizeKey: 'lowConfirmPointSize', symbolKey: 'lowConfirmPointSymbol', defaultStyle: { color: '#26a69a', offsetMultiplier: 0.75, placement: 'below', size: 16, symbol: '\u2191' }, replaces: [] },
]
