export const currencyOverrides: Record<string, string> = {
  CNH: '\u79bb\u5cb8\u4eba\u6c11\u5e01',
  RUR: '\u4fc4\u7f57\u65af\u5362\u5e03',
  XAG: '\u767d\u94f6',
  XAU: '\u9ec4\u91d1',
  XPD: '\u94af\u91d1',
  XPT: '\u94c2\u91d1',
}
export const englishCurrencyAliases: Record<string, string> = {
  forint: 'HUF',
  hryvnia: 'UAH',
  rupiah: 'IDR',
  vatu: 'VUV',
  zloty: 'PLN',
  'algerian dinar': 'DZD',
  'angolan kwanza': 'AOA',
  'argentine peso': 'ARS',
  'armenian dram': 'AMD',
  'australian dollar': 'AUD',
  'azerbaijani manat': 'AZN',
  'bahraini dinar': 'BHD',
  'bangladeshi taka': 'BDT',
  'botswana pula': 'BWP',
  'brazilian real': 'BRL',
  'brunei dollar': 'BND',
  'bulgarian lev': 'BGN',
  'canadian dollar': 'CAD',
  'chilean peso': 'CLP',
  'colombian peso': 'COP',
  'croatian kuna': 'HRK',
  'czech koruna': 'CZK',
  'danish krone': 'DKK',
  'danish krona': 'DKK',
  'egyptian pound': 'EGP',
  euro: 'EUR',
  'georgian lari': 'GEL',
  'ghanaian cedi': 'GHS',
  'great britain pound': 'GBP',
  'guatemalan quetzal': 'GTQ',
  'honduran lempira': 'HNL',
  'hong kong dollar': 'HKD',
  'iceland krona': 'ISK',
  'indian rupee': 'INR',
  'iraqi dinars': 'IQD',
  'israeli shekel': 'ILS',
  'japanese yen': 'JPY',
  'jordanian dinar': 'JOD',
  'kazakhstan tenge': 'KZT',
  'kenyan shilling': 'KES',
  'kuwaiti dinar': 'KWD',
  'lebanese pound': 'LBP',
  'malaysian ringgit': 'MYR',
  'mexican peso': 'MXN',
  'moroccan dirham': 'MAD',
  'nepalese rupee': 'NPR',
  'new israeli shekel': 'ILS',
  'new taiwan dollar': 'TWD',
  'new turkish lira': 'TRY',
  'new zealand dollar': 'NZD',
  'nigerian naira': 'NGN',
  'norwegian krone': 'NOK',
  'norwegian krona': 'NOK',
  'omani rial': 'OMR',
  'pakistan rupee': 'PKR',
  'philippine peso': 'PHP',
  'qatari riyal': 'QAR',
  'romanian leu': 'RON',
  'romanian leu new': 'RON',
  'russian ruble': 'RUB',
  'saudi riyal': 'SAR',
  'singapore dollar': 'SGD',
  'south african rand': 'ZAR',
  'south korea won': 'KRW',
  'sri lankan rupee': 'LKR',
  'swedish krona': 'SEK',
  'swiss franc': 'CHF',
  'syrian pound': 'SYP',
  'tajikistan somoni': 'TJS',
  'tajikistani somoni': 'TJS',
  'thai baht': 'THB',
  'turkmenistan manat': 'TMT',
  'tunisian dinar': 'TND',
  'uganda shilling': 'UGX',
  'united arab emirates dirham': 'AED',
  'us dollar': 'USD',
  'uzbekistan sum': 'UZS',
  'uzbekistani som': 'UZS',
  'vietnamese dong': 'VND',
  'west african cfa': 'XOF',
  'yuan renminbi': 'CNY',
}

export const cryptoNames: Record<string, string> = {
  '1INCH': '1inch',
  AAVE: 'Aave',
  ADA: 'Cardano',
  ALGO: 'Algorand',
  ATOM: 'Cosmos',
  AVAX: 'Avalanche',
  BAT: 'Basic Attention Token',
  BCH: '\u6bd4\u7279\u5e01\u73b0\u91d1',
  BNB: 'BNB',
  BTC: '\u6bd4\u7279\u5e01',
  CAKE: 'PancakeSwap',
  COMP: 'Compound',
  DOGE: 'Dogecoin',
  DOT: 'Polkadot',
  ENJ: 'Enjin Coin',
  EOS: 'EOS',
  ETC: 'Ethereum Classic',
  ETH: '\u4ee5\u592a\u574a',
  FIL: 'Filecoin',
  HBAR: 'Hedera',
  HT: 'Huobi Token',
  ICP: 'Internet Computer',
  IOST: 'IOST',
  LINK: 'Chainlink',
  LTC: 'Litecoin',
  MANA: 'Decentraland',
  MATIC: 'Polygon',
  MBT: '\u5fae\u578b\u6bd4\u7279\u5e01',
  NEAR: 'NEAR',
  SHIB: 'Shiba Inu',
  SNX: 'Synthetix',
  SOL: 'Solana',
  THETA: 'Theta',
  TRX: 'TRON',
  UNI: 'Uniswap',
  XLM: 'Stellar',
  XMR: 'Monero',
  XRP: 'Ripple',
  XTZ: 'Tezos',
  ZEC: 'Zcash',
}
export const commodityNames: Record<string, { name: string; type: string; aliases?: string[] }> = {
  XAU: { name: '\u9ec4\u91d1', type: '\u8d35\u91d1\u5c5e', aliases: ['gold'] },
  XAG: { name: '\u767d\u94f6', type: '\u8d35\u91d1\u5c5e', aliases: ['silver'] },
  XPT: { name: '\u94c2\u91d1', type: '\u8d35\u91d1\u5c5e', aliases: ['platinum'] },
  XPD: { name: '\u94af\u91d1', type: '\u8d35\u91d1\u5c5e', aliases: ['palladium'] },
  XCU: { name: '\u94dc', type: '\u91d1\u5c5e', aliases: ['copper'] },
  XNI: { name: '\u954d', type: '\u91d1\u5c5e', aliases: ['nickel'] },
  XPB: { name: '\u94c5', type: '\u91d1\u5c5e', aliases: ['lead'] },
  XZN: { name: '\u950c', type: '\u91d1\u5c5e', aliases: ['zinc'] },
  XAL: { name: '\u94dd', type: '\u91d1\u5c5e', aliases: ['aluminium', 'aluminum'] },
  XNG: { name: '\u5929\u7136\u6c14', type: '\u80fd\u6e90', aliases: ['natural gas'] },
  XTI: { name: '\u7f8e\u56fd\u539f\u6cb9', type: '\u80fd\u6e90', aliases: ['wti', 'oil'] },
  XBR: { name: '\u5e03\u4f26\u7279\u539f\u6cb9', type: '\u80fd\u6e90', aliases: ['brent'] },
}
export const stockNames: Record<string, string> = {
  AAPL: '\u82f9\u679c',
  ABBV: 'AbbVie',
  ABNB: 'Airbnb',
  ABT: 'Abbott',
  ADBE: 'Adobe',
  ADP: 'ADP',
  AMC: 'AMC',
  AMD: 'AMD',
  AMGN: 'Amgen',
  AMT: 'American Tower',
  AMZN: '\u4e9a\u9a6c\u900a',
  ARM: 'Arm Holdings',
  ATVI: 'Activision Blizzard',
  AVGO: 'Broadcom',
  BA: 'Boeing',
  BABA: '\u963f\u91cc\u5df4\u5df4',
  BAC: 'Bank of America',
  BB: 'BlackBerry',
  BEKE: '\u8d1d\u58f3',
  BIDU: '\u767e\u5ea6',
  BILI: '\u54d4\u54e9\u54d4\u54e9',
  BIIB: 'Biogen',
  BMY: 'Bristol Myers Squibb',
  BRQS: 'Borqs',
  BYD: 'BYD',
  BYND: 'Beyond Meat',
  CAN: 'Canaan',
  C: 'Citigroup',
  COIN: 'Coinbase',
  COST: 'Costco',
  CRM: 'Salesforce',
  CSCO: 'Cisco',
  CVX: 'Chevron',
  DIS: 'Disney',
  EA: 'Electronic Arts',
  EBAY: 'eBay',
  EDU: '\u65b0\u4e1c\u65b9',
  EQIX: 'Equinix',
  F: 'Ford',
  GE: 'GE',
  GM: 'General Motors',
  GOOGL: 'Google',
  GOOG: 'Google',
  HD: 'Home Depot',
  IBM: 'IBM',
  INTC: 'Intel',
  INTU: 'Intuit',
  IQ: '\u7231\u5947\u827a',
  ISRG: 'Intuitive Surgical',
  JD: '\u4eac\u4e1c',
  JNJ: 'Johnson & Johnson',
  JPM: 'JPMorgan Chase',
  KO: 'Coca-Cola',
  LI: '\u7406\u60f3\u6c7d\u8f66',
  LLY: 'Eli Lilly',
  LMT: 'Lockheed Martin',
  MA: 'Mastercard',
  MCD: 'McDonald\'s',
  MDLZ: 'Mondelez',
  META: 'Meta',
  MRK: 'Merck',
  MS: 'Morgan Stanley',
  MSFT: '\u5fae\u8f6f',
  MU: 'Micron',
  MMM: '3M',
  MO: 'Altria',
  NFLX: 'Netflix',
  NIO: '\u851a\u6765',
  NKE: 'Nike',
  NTES: '\u7f51\u6613',
  NVO: 'Novo Nordisk',
  NVDA: 'NVIDIA',
  ORCL: 'Oracle',
  PDD: '\u62fc\u591a\u591a',
  PEP: 'PepsiCo',
  PFE: 'Pfizer',
  PG: 'Procter & Gamble',
  PLTR: 'Palantir',
  PM: 'Philip Morris',
  PYPL: 'PayPal',
  QCOM: 'Qualcomm',
  RACE: 'Ferrari',
  REGN: 'Regeneron',
  RIVN: 'Rivian',
  RLX: '\u96fe\u82af\u79d1\u6280',
  SBUX: 'Starbucks',
  SHEL: 'Shell',
  SHOP: 'Shopify',
  SMCI: 'Super Micro Computer',
  T: 'AT&T',
  TAL: '\u597d\u672a\u6765',
  TCEHY: '\u817e\u8baf\u63a7\u80a1',
  TM: 'Toyota',
  TME: '\u817e\u8baf\u97f3\u4e50',
  TSLA: 'Tesla',
  TSM: 'TSMC',
  UBER: 'Uber',
  UNH: 'UnitedHealth',
  UPS: 'UPS',
  V: 'Visa',
  VIPS: '\u552f\u54c1\u4f1a',
  VRTX: 'Vertex',
  VZ: 'Verizon',
  WFC: 'Wells Fargo',
  WMT: 'Walmart',
  XOM: 'Exxon Mobil',
  XPEV: '\u5c0f\u9e4f\u6c7d\u8f66',
  YUMC: '\u767e\u80dc\u4e2d\u56fd',
  ZTO: '\u4e2d\u901a\u5feb\u9012',
}
export const indexNames: Record<string, string> = {
  AUS200: '\u6fb3\u6d32ASX 200',
  CHINA50: '\u4e2d\u56fdA50',
  DAX40: '\u5fb7\u56fdDAX',
  DE30: '\u5fb7\u56fd30\u6307\u6570',
  DE40: '\u5fb7\u56fdDAX',
  DJI: '\u9053\u743c\u65af\u6307\u6570',
  DXY: '\u7f8e\u5143\u6307\u6570',
  FR40: '\u6cd5\u56fdCAC 40',
  GER40: '\u5fb7\u56fdDAX',
  HK50: '\u6052\u751f\u6307\u6570',
  IN50: '\u5370\u5ea650\u6307\u6570',
  JP225: '\u65e5\u7ecf225',
  NAS100: '\u7eb3\u65af\u8fbe\u514b100',
  SP500: '\u6807\u666e500',
  STOXX50: '\u6b27\u6d32\u65af\u6258\u514b50',
  UK100: '\u82f1\u56fd\u5bcc\u65f6100',
  US100: '\u7eb3\u65af\u8fbe\u514b100',
  US2000: '\u7f57\u7d202000',
  US30: '\u9053\u743c\u65af\u6307\u6570',
  US500: '\u6807\u666e500',
  USTEC: '\u7eb3\u65af\u8fbe\u514b100',
}
